export type Role =
  | "Creator & Protocol Architect"
  | "Co-Founder & Lead Researcher"
  | "Co-Founder & Oracle Specialist"
  | "Founder & Systems Engineer"
  | "Co-Founder & Infrastructure Architect"
  | "Founder & Governance Strategist"
  | "Co-Founder & Scaling Specialist"
  | "Founder & DeFi Specialist"
  | "Founder & Liquidity Strategist"
  | "Founder & Ecosystem Entrepreneur"
  | "Creator & Software Engineer"
  | "Chief Executive & Technical Lead"
  | "Founder & Payments Executive"
  | "Chief Executive & Cryptographer"
  | "Founder & Computer Scientist"
  | "Chief Executive & Industrialist"
  | "Chief Executive & AI Strategist"
  | "Chief Executive & Computing Visionary"
  | "Founder & Financial Tech Executive"
  | "Founder & Social Systems Executive"
  | "Chief Executive & Cloud Strategist"
  | "Chief Executive & Search Technology Lead"
  | "Chief Executive & Founder"
  | "Chief Executive"
  | "Founder & Investor"
  | "Co-Founder & Financial Executive"
  | "Executive Chairman & Treasury Strategist"
  | "Chief Executive & Fund Manager"
  | "Chief Executive & Asset Manager"
  | "Public Figure & Policy Advocate"
  | "Investor & Technologist"
  | "General Partner & Venture Capitalist"
  | "Venture Capitalist"
  | "Investor & Entrepreneur"
  | "Educator & Author"
  | "Investor & Content Creator"
  | "Macro Strategist & Executive"
  | "Educator & Strategist"
  | "Market Analyst"
  | "Quantitative Analyst"
  | "Regulatory Executive"
  | "Regulatory Commissioner"
  | "Advisor & Investor"
  | "Chief Technical Officer"
  | "Founder & Software Engineer"
  | "Founder & Entrepreneur"
  | "Core Developer"
  | "Chief Executive & Infrastructure Lead"
  | "Chief Executive & Software Engineer"
  | "Chief Executive & AI Researcher"
  | "Co-Founder & AI Researcher"
  | "Chief Executive & Academic"
  | "Educator & Content Creator"
  | "Educator & Software Engineer"
  | "Curator & Digital Asset Collector"
  | "Academic & Content Creator"
  | "Chief Marketing Officer"
  | "Futurist & Keynote Speaker"
  | "Journalist & Content Creator"
  | "Founder & Advocate"
  | "General Partner & Investor"
  | "Co-Founder & Investor"
  | "Entrepreneur & Investor"
  | "Advisor & Former Operating Executive"
  | "Managing Partner & Investor"
  | "Executive Chairman & Entrepreneur"
  | "Chief Operating Officer"
  | "Co-Founder & President"
  | "Chief Executive & Payments Strategist"
  | "Chief Executive & Policy Advocate"
  | "Founder & Financial Architect"
  | "Investor & Strategist"
  | "Chief Executive & Entrepreneur"
  | "Advocate & Investor"
  | "General Counsel & Legal Expert"
  | "Chief Financial Officer";

export type PrimaryChain =
  | "BTC"
  | "ETH"
  | "LINK"
  | "SOL"
  | "DOT"
  | "ADA"
  | "POL"
  | "UNI"
  | "AAVE"
  | "TRX"
  | "LTC"
  | "USDT"
  | "USDC"
  | "AVAX"
  | "DOGE/BTC"
  | "WLD"
  | "AI Hardware"
  | "Immersive Tech"
  | "Enterprise AI"
  | "Consumer AI"
  | "BASE"
  | "BNB"
  | "Various"
  | "Policy"
  | "XRP"
  | "AI";

export interface CryptoFigure {
  id: string;
  name: string;
  role: Role;
  primaryChain: PrimaryChain;
  yearJoined: number;
  imageUrl: string;
}
